import argparse


def get_args():
    parser = argparse.ArgumentParser(description="HHNC Args")

    parser.add_argument("--warm_up", default=False, action="store_true")
    parser.add_argument("--memory_size", default=4096, type=int)
    parser.add_argument("--disable_elite_memory", default=False, action="store_true")
    parser.add_argument("--elite_clean_conf_margin", default=0.0, type=float)
    parser.add_argument("--noisy_rate", default=0.4, type=float)
    parser.add_argument("--gmm_initial_threshold", default=0.95, type=float)
    parser.add_argument("--gmm_bank_threshold", default=0.7, type=float)
    parser.add_argument("--noisy_file", default="./noise_file/f30k/noise_inx_0.4.npy", type=str)
    parser.add_argument("--noisy_prior", type=float, default=0.25)
    parser.add_argument("--min_bank_size", type=int, default=1024)

    parser.add_argument("--disable_hhnc", dest="enable_hhnc", action="store_false")
    parser.set_defaults(enable_hhnc=True)
    parser.add_argument("--hhnc_loss_weight", type=float, default=0.1)
    parser.add_argument("--hhnc_use_hyperbolic", action="store_true")
    parser.add_argument("--hhnc_hyper_dim", type=int, default=256)
    parser.add_argument("--hhnc_curvature", type=float, default=1.0)
    parser.add_argument("--hhnc_min_bank_size", type=int, default=1024)
    parser.add_argument("--hhnc_update_interval", type=int, default=100)
    parser.add_argument("--hhnc_max_hierarchy_samples", type=int, default=4096)
    parser.add_argument("--hhnc_max_microcluster_size", type=int, default=32)
    parser.add_argument("--hhnc_fusion_alpha", type=float, default=0.5)
    parser.add_argument("--hhnc_graph_k", type=int, default=16)
    parser.add_argument("--hhnc_graph_threshold", type=float, default=0.55)
    parser.add_argument("--hhnc_kmeans_iters", type=int, default=6)
    parser.add_argument("--hhnc_min_merge_quality", type=float, default=0.05)
    parser.add_argument("--hhnc_min_merge_affinity", type=float, default=0.0)
    parser.add_argument("--hhnc_quality_lambda_c", type=float, default=1.0)
    parser.add_argument("--hhnc_quality_lambda_r", type=float, default=1.0)
    parser.add_argument("--hhnc_quality_lambda_d", type=float, default=1.0)
    parser.add_argument("--hhnc_reliability_lambda_vt", type=float, default=0.5)
    parser.add_argument("--hhnc_reliability_lambda_i2t", type=float, default=0.25)
    parser.add_argument("--hhnc_reliability_lambda_t2i", type=float, default=0.25)
    parser.add_argument("--hhnc_sep_min", type=float, default=0.05)
    parser.add_argument("--hhnc_sep_max", type=float, default=0.75)
    parser.add_argument("--hhnc_sep_tau", type=float, default=0.05)
    parser.add_argument("--hhnc_topk_lca", type=int, default=3)
    parser.add_argument("--hhnc_query_tau", type=float, default=0.07)
    parser.add_argument("--hhnc_query_conf_threshold", type=float, default=0.0)
    parser.add_argument("--hhnc_min_ancestor_depth", type=int, default=1)
    parser.add_argument("--hhnc_noisy_ret_weight", type=float, default=0.5)
    parser.add_argument("--hhnc_parent_margin", type=float, default=0.5)
    parser.add_argument("--hhnc_depth_margin", type=float, default=0.02)
    parser.add_argument("--hhnc_sibling_margin", type=float, default=0.5)
    parser.add_argument("--hhnc_max_sibling_pairs", type=int, default=4096)

    parser.add_argument("--profile_complexity", action="store_true")
    parser.add_argument("--profile_batch_size", type=int, default=64)
    parser.add_argument("--profile_warmup", type=int, default=20)
    parser.add_argument("--profile_iters", type=int, default=100)

    parser.add_argument("--local_rank", default=0, type=int)
    parser.add_argument("--name", default="HHNC")
    parser.add_argument("--output_dir", default="HHNC_Result/")
    parser.add_argument("--log_period", default=500, type=int)
    parser.add_argument("--eval_period", default=1, type=int)
    parser.add_argument("--val_dataset", default="val")
    parser.add_argument("--resume", default=False, action="store_true")
    parser.add_argument("--resume_ckpt_file", default="")

    parser.add_argument("--pretrain_choice", default="ViT-B/32")
    parser.add_argument("--temperature", type=float, default=0.02)
    parser.add_argument("--img_aug", default=False, action="store_true")
    parser.add_argument("--lr_factor", type=float, default=10.0)
    parser.add_argument("--disable_amp", dest="use_amp", action="store_false")
    parser.set_defaults(use_amp=True)

    parser.add_argument("--loss_names", default="InfoNCE", choices=["InfoNCE", "SDM", "TAL"])

    parser.add_argument("--img_size", type=tuple, default=(224, 224))
    parser.add_argument("--stride_size", type=int, default=32)
    parser.add_argument("--text_length", type=int, default=77)

    parser.add_argument("--optimizer", type=str, default="Adam", choices=["SGD", "Adam", "AdamW"])
    parser.add_argument("--lr", type=float, default=1e-6)
    parser.add_argument("--bias_lr_factor", type=float, default=2.0)
    parser.add_argument("--momentum", type=float, default=0.9)
    parser.add_argument("--weight_decay", type=float, default=4e-5)
    parser.add_argument("--weight_decay_bias", type=float, default=0.0)
    parser.add_argument("--alpha", type=float, default=0.9)
    parser.add_argument("--beta", type=float, default=0.999)

    parser.add_argument("--warmup_epochs", type=int, default=5)
    parser.add_argument("--num_epoch", type=int, default=10)
    parser.add_argument("--milestones", type=int, nargs="+", default=(20, 50))
    parser.add_argument("--gamma", type=float, default=0.1)
    parser.add_argument("--warmup_factor", type=float, default=0.1)
    parser.add_argument("--warmup_method", type=str, default="linear")
    parser.add_argument("--lrscheduler", type=str, default="cosine")
    parser.add_argument("--target_lr", type=float, default=0.0)
    parser.add_argument("--power", type=float, default=0.9)

    parser.add_argument("--dataset_name", default="Flickr30k", choices=["Flickr30k", "COCO", "CC120K"])
    parser.add_argument("--sampler", default="random", choices=["identity", "random"])
    parser.add_argument("--num_instance", type=int, default=4)
    parser.add_argument("--root_dir", default="./data")
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--test_batch_size", type=int, default=507)
    parser.add_argument("--num_workers", type=int, default=8)
    parser.add_argument("--test", dest="training", default=True, action="store_false")

    return parser.parse_args()